Doodor.OrganizadorPessoal.Site/Controllers/ContasController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Doodor.OrganizadorPessoal.Application.ViewModels;
using Doodor.OrganizadorPessoal.Application.Interfaces;
using Doodor.OrganizadorPessoal.Domain.Notifications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Doodor.OrganizadorPessoal.Domain.Financeiro.Authentication.Interfaces;
using Doodor.OrganizadorPessoal.Infra.CrossCutting.Identity.Models;

namespace Doodor.OrganizadorPessoal.Site.Controllers
{
    [Authorize]
    public class ContasController : BaseController
    {
        private readonly IContaAppService _contaAppService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ContasController(IContaAppService contaAppService,
            IDomainNotificationHandler<DomainNotification> notifications,
            UserManager<ApplicationUser> userManager,
            IUser user) : base (notifications, user)
        {
            _contaAppService = contaAppService;
            _userManager = userManager;
        }
              
        public IActionResult Index()
        {
            try
            {
                var id = _userManager.GetUserId(User);                
                var result = _contaAppService.ObterTodos(Guid.Parse(id));

                if(TempData["RetornoPost"] != null)
                    ViewBag.RetornoPost = TempData["RetornoPost"].ToString();

                return View(result);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return NotFound();
            }
        }

        // GET: ContaViewModels/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaViewModel = _contaAppService.ObterPorId(id.Value);                
            if (contaViewModel == null)
            {
                return NotFound();
            }

            return View(contaViewModel);
        }

        // GET: ContaViewModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ContaViewModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ContaViewModel contaViewModel)
        {
            if (!ModelState.IsValid) return View(contaViewModel);

            contaViewModel.UsuarioId = UsuarioId;

            _contaAppService.CriarConta(contaViewModel);

            if (OperacaoValida())
            {
                TempData["RetornoPost"] = "success, Operação realizada com sucesso";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.RetornoPost = "error, Operação não realizada";
                return View(contaViewModel);
            }            
        }
        
        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaViewModel = _contaAppService.ObterPorId(id);
            if (contaViewModel == null)
            {
                return NotFound();
            }
            return View(contaViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, ContaViewModel contaViewModel)
        {
            if (id != contaViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    contaViewModel.UsuarioId = UsuarioId;

                    _contaAppService.AtualizarConta(contaViewModel);
                    if (OperacaoValida())
                    {
                        TempData["RetornoPost"] = "success, Operação realizada com sucesso";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.RetornoPost = "error, Operação não realizada";
                        return View(contaViewModel);
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                    return NotFound();
                }
                
            }
            else
            {
                return View(contaViewModel);
            }
        }
        
        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaViewModel = _contaAppService.ObterPorId(id);
            if (contaViewModel == null)
            {
                return NotFound();
            }

            return View(contaViewModel);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _contaAppService.DeletarConta(id);

            if (OperacaoValida())
            {
                TempData["RetornoPost"] = "success, Operação realizada com sucesso";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.RetornoPost = "error, Operação não realizada";
                return View(id);
            }            
        }  
    }
}

Doodor.OrganizadorPessoal.Site/ViewComponents/SummaryViewComponent.cs
using Doodor.OrganizadorPessoal.Domain.Notifications;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Doodor.OrganizadorPessoal.Site.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        private  readonly IDomainNotificationHandler<DomainNotification> _notifications;

        public SummaryViewComponent(IDomainNotificationHandler<DomainNotification> notifications)
        {
            _notifications = notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.GetNotifications());

            notificacoes.ForEach(c=> ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

Doodor.OrganizadorPessoal.Site/Views/Contas/Create.cshtml
@model Doodor.OrganizadorPessoal.Application.ViewModels.ContaViewModel
@using Doodor.OrganizadorPessoal.Application.ViewModels

@{
    ViewData["Title"] = "Criar Conta";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Cadastro de Contas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a>Financeiro</a>
            </li>
            <li class="active">
                <strong>Contas</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Cadastro de contas</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <br/>
                    <form asp-action="Create" class="form-horizontal">

                        @await Html.PartialAsync("_CamposForm",Model)
                    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    @if (ViewBag.RetornoPost != null)
    {
        var notificacao = ViewBag.RetornoPost.ToString().Split(",");
         
    <script>
        
        toastr.options = {
            "closeButton": false,
            "debug": true,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-top-right",
            "preventDuplicates": true,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr["@notificacao[0]"]("@notificacao[1]");
    </script>
    }
    }

Doodor.OrganizadorPessoal.Site/Views/Contas/Delete.cshtml
@model Doodor.OrganizadorPessoal.Application.ViewModels.ContaViewModel

@{
    ViewData["Title"] = "Delete";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Exclusão de contas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a>Financeiro</a>
            </li>
            <li class="active">
                <strong>Contas</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="ibox float-e-margins">                                                            
                <div class="ibox-title">
                    <h5>Confirmar Exclusão?</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                    <br />
                    <div class="text-right">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Deletar" class="btn btn-danger" />
                            <a asp-action="Index" class="btn btn-white">Cancelar</a>
                        </form>
                    </div>

                </div>

                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-6">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Nome)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Nome)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.ValorTotal)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.ValorTotal)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.DataPrimeiroPgto)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.DataPrimeiroPgto)
                                </dd>
                            </dl>
                        </div>
                        <div class="col-md-6">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.FrequenciaDiaPgto)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.FrequenciaDiaPgto)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.PorcVariacaoMensal)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.PorcVariacaoMensal)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.QtdParcelas)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.QtdParcelas)
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Doodor.OrganizadorPessoal.Site/Views/Contas/Details.cshtml
@model Doodor.OrganizadorPessoal.Application.ViewModels.ContaViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Detalhes de Contas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a>Financeiro</a>
            </li>
            <li class="active">
                <strong>Contas</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Detalhes da Conta</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                    <br />
                    <div class="text-right">
                        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Editar</a>
                        <a asp-action="Index" class="btn btn-white">Voltar</a>
                    </div>
                </div>


                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-6">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Nome)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Nome)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.ValorTotal)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.ValorTotal)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.DataPrimeiroPgto)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.DataPrimeiroPgto)
                                </dd>
                            </dl>
                        </div>
                        <div class="col-md-6">
                            <dl class="dl-horizontal">                         
                                <dt>
                                    @Html.DisplayNameFor(model => model.FrequenciaDiaPgto)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.FrequenciaDiaPgto)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.PorcVariacaoMensal)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.PorcVariacaoMensal)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.QtdParcelas)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.QtdParcelas)
                                </dd>
                            </dl>
                        </div>
                    </div>

                    <hr />

                    <div class="table-responsive">
                        <table class="table table-hover ">
                            <thead>
                                <tr>
                                    <th>Numero</th>
                                    <th>Data Parcela</th>
                                    <th>Valor</th>
                                    <th>Pago</th>
                                    <th>Data Pagamento</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var parcela in Model.Parcelas)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => parcela.Numero)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => parcela.DataParcela)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => parcela.Valor)
                            </td>
                            <td>
                                @if (parcela.Pago)
                    {
                        @Html.DisplayName("Paga")
        }
        else
        {
            @Html.DisplayName("Não paga")
}
                            </td>
                            @if (parcela.Pago)
                {
                    <td>
                        @Html.DisplayFor(modelItem => parcela.DataPgto)
                    </td>
    }
    else
    {
            <td>-</td>
}
                        </tr>
        }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Doodor.OrganizadorPessoal.Site/Views/Contas/Edit.cshtml
@model Doodor.OrganizadorPessoal.Application.ViewModels.ContaViewModel
@using Doodor.OrganizadorPessoal.Application.ViewModels

@{
    ViewData["Title"] = "Editar Conta";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Edição de Contas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a>Financeiro</a>
            </li>
            <li class="active">
                <strong>Contas</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edição de contas</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <br />
                    <form asp-action="Edit" class="form-horizontal">
                        <input type="hidden" asp-for="Id" />
                        <vc:summary />
                        @await Html.PartialAsync("_CamposForm", Model)
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    @if (ViewBag.RetornoPost != null)
    {
        var notificacao = ViewBag.RetornoPost.ToString().Split(",");

        <script>

        toastr.options = {
            "closeButton": false,
            "debug": true,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-top-right",
            "preventDuplicates": true,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr["@notificacao[0]"]("@notificacao[1]");
        </script>
    }
}

Doodor.OrganizadorPessoal.Site/Views/Contas/Index.cshtml
@model IEnumerable<Doodor.OrganizadorPessoal.Application.ViewModels.ContaViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Gestão de Contas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a>Financeiro</a>
            </li>
            <li class="active">
                <strong>Contas</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="ibox float-e-margins">    
                <div class="ibox-title">
                    <h5>Lista de contas</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                    <br/>
                    <div class="text-right">
                        <a asp-action="Create" class="btn btn-success btn-fw">Nova Conta</a>
                    </div>
                </div>


                <div class="ibox-content">
                    <div class="row">
                        <div class="table-responsive">
                            </br>
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.Nome)</th>
                                        <th>@Html.DisplayNameFor(model => model.ValorTotal)</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ValorTotal)
                            </td>
                            <td class="text-right">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-route-id="@item.Id">
                                        <button type="button" class="btn btn-o btn-info"><i class="icon fa fa-align-justify"></i></button>
                                    </a>
                                    <a asp-action="Edit" asp-route-id="@item.Id">
                                        <button type="button" class="btn btn-o btn-warning"><i class="icon fa fa-edit"></i></button>
                                    </a>
                                    <a asp-action="Delete" asp-route-id="@item.Id">
                                        <button type="button" class="btn btn-o btn-danger"><i class="icon fa fa-trash-o"></i></button>
                                    </a>
                                </div>
                            </td>
                        </tr>
    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    </div>
                </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    @if (ViewBag.RetornoPost != null)
    {
        var notificacao = ViewBag.RetornoPost.ToString().Split(",");

        <script>

        toastr.options = {
            "closeButton": false,
            "debug": true,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-top-right",
            "preventDuplicates": true,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr["@notificacao[0]"]("@notificacao[1]");
        </script>
    }
}

Doodor.OrganizadorPessoal.Site/Views/Contas/_CamposForm.cshtml
@model Doodor.OrganizadorPessoal.Application.ViewModels.ContaViewModel
@using Doodor.OrganizadorPessoal.Application.ViewModels

@{
    ViewData["Title"] = "Delete";
}
<vc:summary />

<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
            <label asp-for="Nome" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input asp-for="Nome" class="form-control" placeholder="Insira o Nome" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group row">
            <label asp-for="ValorTotal" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input asp-for="ValorTotal" class="form-control" placeholder="Valor total" />
            </div>
            <span asp-validation-for="ValorTotal" class="text-danger"></span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
            <label asp-for="DataPrimeiroPgto" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input asp-for="DataPrimeiroPgto" class="form-control" placeholder="Data primeiro pagamento" />
                <span asp-validation-for="DataPrimeiroPgto" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group row">
            <label asp-for="FrequenciaDiaPgto" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                @{
                    var frequenciasPgto = (IEnumerable<SelectListItem>)ContaViewModel.GetSelectListFrequenciaPgto();
                }
                <select asp-for="FrequenciaDiaPgto" asp-items="@frequenciasPgto" class="form-control"></select>
                <span asp-validation-for="FrequenciaDiaPgto" class="text-danger"></span>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group row">
            <label asp-for="PorcVariacaoMensal" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input asp-for="PorcVariacaoMensal" class="form-control" placeholder="Porcentagem variação mensal" />
                <span asp-validation-for="PorcVariacaoMensal" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group row">
            <label asp-for="QtdParcelas" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input asp-for="QtdParcelas" class="form-control" placeholder="Quantidade de parcelas" />
                <span asp-validation-for="QtdParcelas" class="text-danger"></span>
            </div>
        </div>
    </div>
</div>
<div class="form-group text-right">
    <input type="submit" value="Criar" class="btn btn-success mr-2" />
    <a asp-action="Index" class="btn btn-white">Cancelar</a>
</div>