Doodor.OrganizadorPessoal.Site/Controllers/ContasController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Doodor.OrganizadorPessoal.Application.ViewModels;
using Doodor.OrganizadorPessoal.Application.Interfaces;
using Doodor.OrganizadorPessoal.Domain.Notifications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Doodor.OrganizadorPessoal.Domain.Financeiro.Authentication.Interfaces;
using Doodor.OrganizadorPessoal.Infra.CrossCutting.Identity.Models;

namespace Doodor.OrganizadorPessoal.Site.Controllers
{
    [Authorize]
    public class ContasController : BaseController
    {
        private readonly IContaAppService _contaAppService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ContasController(IContaAppService contaAppService,
            IDomainNotificationHandler<DomainNotification> notifications,
            UserManager<ApplicationUser> userManager,
            IUser user) : base (notifications, user)
        {
            _contaAppService = contaAppService;
            _userManager = userManager;
        }
              
        public IActionResult Index()
        {
            try
            {
                var id = _userManager.GetUserId(User);                
                var result = _contaAppService.ObterTodos(Guid.Parse(id));

                if(TempData["RetornoPost"] != null)
                    ViewBag.RetornoPost = TempData["RetornoPost"].ToString();

                return View(result);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                return NotFound();
            }
        }

        // GET: ContaViewModels/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaViewModel = _contaAppService.ObterPorId(id.Value);                
            if (contaViewModel == null)
            {
                return NotFound();
            }

            return View(contaViewModel);
        }

        // GET: ContaViewModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ContaViewModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ContaViewModel contaViewModel)
        {
            if (!ModelState.IsValid) return View(contaViewModel);

            contaViewModel.UsuarioId = UsuarioId;

            _contaAppService.CriarConta(contaViewModel);

            if (OperacaoValida())
            {
                TempData["RetornoPost"] = "success, Operação realizada com sucesso";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.RetornoPost = "error, Operação não realizada";
                return View(contaViewModel);
            }            
        }
        
        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaViewModel = _contaAppService.ObterPorId(id);
            if (contaViewModel == null)
            {
                return NotFound();
            }
            return View(contaViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, ContaViewModel contaViewModel)
        {
            if (id != contaViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    contaViewModel.UsuarioId = UsuarioId;

                    _contaAppService.AtualizarConta(contaViewModel);
                    if (OperacaoValida())
                    {
                        TempData["RetornoPost"] = "success, Operação realizada com sucesso";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.RetornoPost = "error, Operação não realizada";
                        return View(contaViewModel);
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                    return NotFound();
                }
                
            }
            else
            {
                return View(contaViewModel);
            }
        }
        
        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contaViewModel = _contaAppService.ObterPorId(id);
            if (contaViewModel == null)
            {
                return NotFound();
            }

            return View(contaViewModel);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _contaAppService.DeletarConta(id);

            if (OperacaoValida())
            {
                TempData["RetornoPost"] = "success, Operação realizada com sucesso";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.RetornoPost = "error, Operação não realizada";
                return View(id);
            }            
        }  
    }
}

Doodor.OrganizadorPessoal.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrganizadorPessoal - Doodor</title>

    <link rel="shortcut icon" href="favicon.png">

    <environment include="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/plugins/toastr/toastr.min.css" rel="stylesheet" asp-append-version="true" />       
        <link href="~/js/plugins/gritter/jquery.gritter.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/animate.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/plugins/toastr/toastr.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/js/plugins/gritter/jquery.gritter.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/animate.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>
<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <span>
                                <img alt="image" class="img-circle" src="~/images/profile_small.jpg" />
                            </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-t-xs">
                                        <strong class="font-bold">Pedro Vinicius</strong>
                                    </span> <span class="text-muted text-xs block">Developer <b class="caret"></b></span>
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="#">Profile</a></li>
                                <li class="divider"></li>
                                <li>
                                    <a asp-area="" asp-controller="Account" asp-action="Logout">Log out</a>                                    
                                </li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            CP
                        </div>
                    </li>
                    <li class="active">
                        <a href="#">
                            <i class="fa fa-usd"></i>
                            <span class="nav-label">Financeiro</span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li class="active">
                                <a asp-controller="Contas" asp-action="Index">
                                    <i class="icon fa fa-circle-o"></i>
                                    <span>Contas</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
        </nav>
    </div>        
        <!-- /Header -->
        <!-- Main container -->
    <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>  
                </div>                
            </nav>
        </div>
        @RenderBody()
    </div>
            
        
        <!-- /Main container -->

        <environment include="Development">
            <script src="~/js/jquery-3.1.1.min.js" asp-append-version="true"></script>
            <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/metisMenu/jquery.metisMenu.js" asp-append-version="true"></script>
            <script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.tooltip.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.spline.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.resize.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.pie.js" asp-append-version="true"></script>
            <script src="~/js/plugins/peity/jquery.peity.min.js" asp-append-version="true"></script>
            <script src="~/js/demo/peity-demo.js" asp-append-version="true"></script>
            <script src="~/js/inspinia.js" asp-append-version="true"></script>
            <script src="~/js/plugins/pace/pace.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/jquery-ui/jquery-ui.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/gritter/jquery.gritter.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/sparkline/jquery.sparkline.min.js" asp-append-version="true"></script>
            <script src="~/js/demo/sparkline-demo.js" asp-append-version="true"></script>
            <script src="~/js/plugins/chartJs/Chart.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/toastr/toastr.min.js" asp-append-version="true"></script>            
        </environment>
        <environment exclude="Development">
            <script src="~/js/jquery-3.1.1.min.js" asp-append-version="true"></script>
            <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/metisMenu/jquery.metisMenu.js" asp-append-version="true"></script>
            <script src="~/js/plugins/slimscroll/jquery.slimscroll.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.tooltip.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.spline.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.resize.js" asp-append-version="true"></script>
            <script src="~/js/plugins/flot/jquery.flot.pie.js" asp-append-version="true"></script>
            <script src="~/js/plugins/peity/jquery.peity.min.js" asp-append-version="true"></script>
            <script src="~/js/demo/peity-demo.js" asp-append-version="true"></script>
            <script src="~/js/inspinia.js" asp-append-version="true"></script>
            <script src="~/js/plugins/pace/pace.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/jquery-ui/jquery-ui.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/gritter/jquery.gritter.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/sparkline/jquery.sparkline.min.js" asp-append-version="true"></script>
            <script src="~/js/demo/sparkline-demo.js" asp-append-version="true"></script>
            <script src="~/js/plugins/chartJs/Chart.min.js" asp-append-version="true"></script>
            <script src="~/js/plugins/toastr/toastr.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
</body>
</html>

Doodor.OrganizadorPessoal.Site/Views/Shared/_LayoutAuth.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrganizadorPessoal - Doodor</title>

    <link rel="shortcut icon" href="favicon.png">

    <environment include="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/animate.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/animate.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>
<body class="gray-bg">
    <!-- Main container -->
    
    @RenderBody()
    <!-- /Main container -->

    @RenderSection("Scripts", required: false)
</body>
</html>